### ISSUE TITLE
Sayko Bir bot

### ISSUE THREAD

**Issue by BerkPW** [Admicos/DiscordBot#3]
:regional_indicator_b: 
bunun gibi harfleri kullanarak
!isim <name> yazdığımızda adamın yazdığı latin harfleri ile oluşan yazıyı :regional_indicator_b:  bu harflere çevirsin

**Comment by Admicos** [comment]
![](http://image.prntscr.com/image/f217f96f1f1144f7a25873236709289b.png)
Bütün karakterler dönüşemiyor :/

**Comment by BerkPW** [comment]
İngilizce kullan sadece

**Comment by Admicos** [comment]
İkinci karakter'in B olması lazım ama bayrak çıktı nedense

**Comment by BerkPW** [comment]
değişik
neden böyle oldu
